---
- name: Create Logstash configuration files.
  template:
    src: "{{ item }}"
    dest: "{{ logstash_config_dir }}/conf.d/{{ item | basename | regex_replace('\\.j2$') }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ logstash_configuration_files }}"
  notify: reload logstash

- name: Find non-managed files in config dir
  find:
    paths: "{{ logstash_config_dir  }}/conf.d"
    # Only Ansible 2.5
    # excludes: "{{ logstash_configuration_files | map('basename') | map('regex_replace', '\\.j2$') | join(',') }}"
  register: logstash_current_configuration_files

- name: Purge non-managed files in config dir
  file:
    path: "{{ logstash_config_dir  }}/conf.d/{{ item }}"
    state: absent
  # Not needed when Ansible 2.5
  when: (item | basename) not in (logstash_configuration_files | map('basename') | map('regex_replace', '\\.j2$'))
  with_items: "{{ logstash_current_configuration_files.files | map(attribute='path') | list }}"

- name: Create custom patterns dir
  file:
    path: "{{ logstash_config_dir }}/conf.d/patterns"
    state: directory

- name: Create custom patterns file
  copy:
    src: "{{ logtash_custom_patterns_file }}"
    dest: "{{ logstash_config_dir }}/conf.d/patterns/custom"
    owner: root
    group: root
    mode: 0644
  when: logtash_custom_patterns_file is defined
  notify: restart logstash

- name: Install Logstash ES custom templates
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_config_dir }}/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ logstash_es_templates }}"
  notify: reload logstash

- name: Logstash pipeline workers tunning
  lineinfile:
    path: "{{ logstash_config_dir }}/logstash.yml"
    regexp: '^(# )?pipeline.workers: '
    line: "pipeline.workers: {{logstash_pipeline_workers}}"
  when: not ansible_check_mode and logstash_pipeline_workers is defined
  notify: reload logstash

- name: Logstash pipeline batch size tunning
  lineinfile:
    path: "{{ logstash_config_dir }}/logstash.yml"
    regexp: '^(# )?pipeline.batch.size: '
    line: "pipeline.batch.size: {{logstash_pipeline_batch_size}}"
  when: not ansible_check_mode and logstash_pipeline_batch_size is defined
  notify: reload logstash

- name: Logstash pipeline batch delay tunning
  lineinfile:
    path: "{{ logstash_config_dir }}/logstash.yml"
    regexp: '^(# )?pipeline.batch.delay: '
    line: "pipeline.batch.delay: {{logstash_pipeline_batch_delay}}"
  when: not ansible_check_mode and logstash_pipeline_batch_delay is defined
  notify: reload logstash

- include: jvm_options.yml
